name: CI Pipeline - QA Automation

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Ejecutar pruebas y generar reporte HTML
      run: mvn clean test surefire-report:report

    - name: Publicar Reporte Navegable (Artefacto)
      if: always() # Asegura que el reporte se suba incluso si fallan los tests
      uses: actions/upload-artifact@v3
      with:
        name: reporte-pruebas-html
        path: target/site/surefire-report.html
